[package]
name = "plaintext_wasm"
version = "0.1.0"
authors = ["gustin <gustin@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.opaque]
path = "../opaque"

